### ISSUE TITLE
How to extend to distributed mpc case

### ISSUE THREAD

**Issue by liliya201104** [HiroIshida/robust-tube-mpc#11]
Hi, thank you for your code again! 

Can this code extend to distributed model predictive control? I see that the  `OptimalControler` class is only for objective function V(s) = s'*H*S. While in the distributed form, the cost function is V(s) = sum(x_i-x_j)'*Q*(x_i-x_j)+u_i'Ru_i  for all its neighbors j and only x_i is the decision variable, x_j is known. So, do you know how to update this code for the dsitributed cost function?

Thank you very much!

**Comment by HiroIshida** [comment]
I'm a robot engineer and not a mpc guy actually, so could you provide specific academic paper (+ page number and equation number, hopefully) so that I can see the equation? I don't know but, I guess it's not so difficult

**Comment by liliya201104** [comment]
The distributed tube MPC is shown in paper "Cooperative distributed MPC of linear systems with coupled constraints". 

The optimization problem is shown in equation (5) and (6). The cooperative algorithm is shown in Algorithm 1.

But I want to change the cost function to 
![image](https://user-images.githubusercontent.com/26400278/88242841-73b5ab80-ccc9-11ea-9d91-0b0dfc1ad02a.png). 

How to extend the code to this case? Do you have any suggestion? Thank you very much!

**Comment by HiroIshida** [comment]
OK, I will look it later. By the way pasting an academic paper which is not free here is not good (you know, copyright stuff). So could you edit and replace the pdf by just the paper title?

**Comment by liliya201104** [comment]
Ok, I got it. Thank you very much!

**Comment by HiroIshida** [comment]
I guess you forget `\Sigma_{q\in\mathcal{N}_p(k)}` before the first term (probably terminal cost)? I mean `q` should be a bounded variable. If so, I think it's easy to implement, but bit difficult to explain so please wait a sec.

**Comment by liliya201104** [comment]
Yes, you are right. I want to obtain the optimization solution of agent p. The decision variable is 
![image](https://user-images.githubusercontent.com/26400278/88248672-ea0fd900-ccdc-11ea-9dd5-0c75941c2a1f.png)
 q is the neighbor of agent p and the number of q is limited. The cost function is changed to 
![image](https://user-images.githubusercontent.com/26400278/88248445-373f7b00-ccdc-11ea-9ccb-c99468d6dbc7.png)

The communication is assumed to be unchanged during the process.

**Comment by HiroIshida** [comment]
The following note is my suggestion. 
[idea.pdf](https://github.com/HiroIshida/robust-tube-mpc/files/4963888/idea.pdf)
efc770b
Note that, in my implementation, the optimization variable fro quadprog is S = [X, U] = [x1, ..., xn, u1,..., un], (looks strange and actually inefficient) but I put a set dynamical constraints to equality constraints.

**Comment by liliya201104** [comment]
Ok, many thanks for your great help!
