### ISSUE TITLE
questions: running examples

### ISSUE THREAD

**Issue by MahdiehSadabadi** [HiroIshida/robust-tube-mpc#3]
Hi,

I have been trying to run the examples. However, I have not been able to do it. The main issue is about the command "mpc.simulate(Tsimu, x_init)" in the examples. I have got the following errors:
Error using mskoptimset (line 67)
Expected argument 2 to be a string parameter name or an options structure
created with mskoptimset.
Error in quadprog (line 78)
options          = mskoptimset(defaultopt,options);
Error in OptimalControler/solve (line 62)
                [var_optim, ~, exitflag] = quadprog(obj.H, [], C_neq1_relaxed, obj.C_neq2, obj.C_eq1, obj.C_eq2(x_init), [], [], [], options);
Error in TubeModelPredictiveControl/simulate (line 52)
            [x_nominal_seq, u_nominal_seq] = obj.optcon.solve(x_init); 

Do you know why I have got these errors?

**Comment by liliya201104** [comment]
Hi, I have the same question. Have you solved this problem?

**Comment by HiroIshida** [comment]
answerd in 
https://github.com/HiroIshida/robust-tube-mpc/issues/10
