### ISSUE TITLE
some confusion

### ISSUE THREAD

**Issue by sqinging** [HiroIshida/robust-tube-mpc#8]
hi, appreciating your code on RMPC,
is there possible to revise it into a model with 4 state+1 input+2output ?

The "tube" can be feasible ? hoping for answer

**Comment by HiroIshida** [comment]
@sqinging Thanks for the feedback :) I think we can handle any dimension of state and input. But I did not fully tested yet, and I'm currently having trouble installing matlab, so wait for moment (maybe couple of weeks). 

I don't understand what do you mean by "output". As far as I know, RMPC is nothing to do with observation, so I think you don't have to care about the output (observation) dimension. 

>> The "tube" can be feasible ?

sorry, I don't understand
