### ISSUE TITLE
Trying to understand how F and G matrices are constructed

### ISSUE THREAD

**Issue by GPrathap** [HiroIshida/robust-tube-mpc#9]
I am trying to understand, how F and G matrices are constructed from X and U matrixes

How have you decided these are the constraints for U and X: https://github.com/HiroIshida/robust-tube-mpc/blob/master/example/example_tubeMPC.m#L19

Thanks

**Comment by HiroIshida** [comment]
I think to understand how the X and U matrices are converted to F and G, the following slide, which I presented 2 years ago in the lab will be helpful. So I make a link of the slide from my dropbox here: 
https://www.dropbox.com/s/9i9vl3irroge6fq/Model%20Predictive%20Control.pptx?dl=0

Slide p. 4 exactly explains about this. Also, slide p. 7 ~ 9 will be helpful to understand how the MPI set is computed [here]( https://github.com/HiroIshida/robust-tube-mpc/blob/b82f0c40eed287eaafac097aa5990ded35b301b5/src/LinearSystem.m#L31) without using p. 11 ~ 12.

**Comment by GPrathap** [comment]
Thank you so much, with your awesome presentation, things are much clear now, Thank you again.

**Comment by GPrathap** [comment]
![Selection_117](https://user-images.githubusercontent.com/7587302/87961955-236afd80-cabf-11ea-9f96-bbbe63391818.png)

Sorry, page 5 in your presentation, part of the F matrix corresponding to x_2, should it be as follows? I mean 2 instead of -2 
![CodeCogsEqn](https://user-images.githubusercontent.com/7587302/87962290-a1c79f80-cabf-11ea-9aa9-044c1445cb4c.gif)

**Comment by HiroIshida** [comment]
yeah, you are right. it must be a typo

**Comment by GPrathap** [comment]
Yeah, Thank you so much again.
